- frontend/src/modules/admin/store-orders/barista/components/admin-barista-orders-list.vue
- frontend/src/modules/admin/store-orders/barista/hooks/use-orders-event.hook.ts
- frontend/src/modules/kiosk/cart/components/kiosk-cart-update-item.vue
> fix: fixed error with new status

- docker-compose.yml
> feat: make frontend parallel to backend

- .github/workflows/ci.yml
- frontend/src/modules/admin/products/components/create/admin-product-size-create-form.vue
- frontend/src/modules/admin/products/components/details/admin-product-size-details-form.vue
added product size with unit name and fixed bug with sorting active additives
Link to Asana:
1. https://app.asana.com/1/1206511942979507/project/1208604769421738/task/1209650451283659
2. https://app.asana.com/1/1206511942979507/project/1208604769421738/task/1209650451283660
Sprint number: PI 1, Sprint 9
> added product size with unit name and fixed bug with sorting active additives

- frontend/src/modules/admin/warehouse-stocks/components/admin-select-available-to-add-stock-materials-dialog.vue
Link to Asana: https://app.asana.com/1/1206511942979507/project/1208604769421738/task/1209664873361178
Sprint number: PI 1, Sprint 9
> added package size and unit

- backend/internal/modules/additives/additive.service.go
- backend/internal/modules/stockRequests/stock_requests.repository.go
- frontend/src/modules/admin/additive-categories/components/list/admin-additive-categories-toolbar.vue
- frontend/src/modules/admin/additives/components/list/admin-additives-toolbar.vue
- frontend/src/modules/admin/employees/admins/components/list/admin-admin-employees-toolbar.vue
- frontend/src/modules/admin/employees/franchisees/components/list/admin-franchisees-employees-toolbar.vue
- frontend/src/modules/admin/ingredient-categories/components/list/admin-ingredient-categories-toolbar.vue
- frontend/src/modules/admin/ingredients/components/list/admin-ingredients-toolbar.vue
- frontend/src/modules/admin/products/components/list/admin-products-toolbar.vue
- frontend/src/modules/admin/regions/components/list/admin-regions-toolbar.vue
- frontend/src/modules/admin/stock-material-categories/components/list/admin-stock-material-categories-toolbar.vue
- frontend/src/modules/admin/stock-materials/components/list/admin-stock-materials-toolbar.vue
- frontend/src/modules/admin/stock-requests/components/list/admin-stock-requests-toolbar.vue
- frontend/src/modules/admin/store-additives/components/list/admin-store-additives-toolbar.vue
- frontend/src/modules/admin/store-orders/components/list/admin-store-orders-toolbar.vue
- frontend/src/modules/admin/store-products/components/list/admin-store-products-toolbar.vue
- frontend/src/modules/admin/store-stocks/components/list/admin-store-stocks-toolbar.vue
- frontend/src/modules/admin/stores/components/list/admin-stores-toolbar.vue
- frontend/src/modules/admin/suppliers/components/list/admin-suppliers-toolbar.vue
- frontend/src/modules/admin/units/components/list/admin-units-toolbar.vue
- frontend/src/modules/admin/warehouse-deliveries/components/list/admin-warehouse-deliveries-toolbar.vue
- frontend/src/modules/admin/warehouse-stocks/components/list/admin-warehouse-stocks-toolbar.vue
- frontend/src/modules/admin/warehouses/components/list/admin-warehouses-toolbar.vue
> fix: pagination spoiling the search

- infrastructure/terraform/digital-ocean-droplet-auto/.terraform.lock.hcl
- infrastructure/terraform/digital-ocean-droplet-auto/main.tf
- infrastructure/terraform/digital-ocean-droplet/.terraform.lock.hcl
- infrastructure/terraform/digital-ocean-droplet/main.tf
- infrastructure/terraform/digital-ocean-droplet/variables.tf
> feat: reafcatored terraform methods

- backend/go.mod
- backend/go.sum
- backend/internal/modules/additives/storeAdditivies/types/storeAdditive.dtos.go
- backend/internal/modules/additives/types/additive.dtos.go
- backend/migrations/000002_zero_price.down.sql
- backend/migrations/000002_zero_price.up.sql
> feat: allow zero prices on additives

- frontend/src/modules/admin/stock-materials/components/details/admin-stock-material-details-form.vue
- frontend/src/modules/admin/store-products/components/list/admin-store-products-list.vue
- frontend/src/modules/kiosk/cart/components/checkouts/kiosk-cart-wrapper.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-details-additives-section.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-product-recipe-dialog.vue
- frontend/src/modules/kiosk/products/components/home/kiosk-home-product-card.vue
- frontend/src/modules/kiosk/products/components/home/toolbar/kiosk-home-toolbar-categories.vue
- frontend/src/modules/kiosk/products/components/home/toolbar/kiosk-home-toolbar-search.vue
- frontend/src/modules/kiosk/products/pages/kiosk-home-page.vue
- frontend/src/modules/kiosk/products/pages/kiosk-product-page.vue
> fixed issues on kiosk products

- frontend/src/modules/kiosk/cart/pages/kiosk-cart-payment-page.vue
- frontend/src/modules/kiosk/products/pages/kiosk-home-page.vue
> fix: fixed issue with swiper of categories, hide back button on payment

- frontend/src/modules/admin/store-orders/services/orders.service.ts
> feat: removed unusued order endpoints

- backend/migrations/000004_zero_price_suborder_additives.down.sql
- backend/migrations/000004_zero_price_suborder_additives.up.sql
> fix: migration update

- frontend/src/modules/kiosk/cart/components/kiosk-cart-update-item.vue
- frontend/src/modules/kiosk/products/components/home/list/kiosk-home-products-grid.vue
- frontend/src/modules/kiosk/products/components/home/list/kiosk-home-products-loading.vue
- frontend/src/modules/kiosk/products/components/home/list/kiosk-home-search-products.vue
> fix: fixed component in the cart item component

- backend/internal/container/modules/additives.module.go
- backend/internal/container/modules/products.module.go
- backend/internal/data/audit.data.go
- backend/internal/modules/additives/technicalMap/technicalMap.handler.go
- backend/internal/modules/additives/technicalMap/technicalMap.repository.go
- backend/internal/modules/additives/technicalMap/technicalMaps.service.go
- backend/internal/modules/additives/technicalMap/types/conversion.utils.go
- backend/internal/modules/additives/technicalMap/types/errors.go
- backend/internal/modules/additives/technicalMap/types/responses.go
- backend/internal/modules/additives/technicalMap/types/technicalMap.dtos.go
- backend/internal/modules/product/technicalMap/technicalMap.handler.go
- backend/internal/modules/product/technicalMap/technicalMap.repository.go
- backend/internal/modules/product/technicalMap/technicalMaps.service.go
- backend/internal/modules/product/technicalMap/types/conversion.utils.go
- backend/internal/modules/product/technicalMap/types/errors.go
- backend/internal/modules/product/technicalMap/types/responses.go
- backend/internal/modules/product/technicalMap/types/technicalMap.dtos.go
- backend/internal/routes/employees.routes.go
- backend/scripts/CREATE_MOCK_DATA.sql
> feat: get tech map endpoints(additive. productSize)

- backend/internal/modules/orders/orders.repository.go
- frontend/src/modules/admin/store-orders/hooks/use-order-qr-print.hook.ts
> feat: added print index of suborder

- backend/internal/modules/orders/orders-websocket.service.go
- frontend/src/core/hooks/use-copy-technical-map.hooks.ts
- frontend/src/modules/admin/additives/components/create/admin-additive-create-form.vue
- frontend/src/modules/admin/additives/components/details/admin-additive-details-form.vue
- frontend/src/modules/admin/additives/models/additives.model.ts
- frontend/src/modules/admin/additives/services/additives.service.ts
- frontend/src/modules/admin/products/components/create/admin-product-create-form.vue
- frontend/src/modules/admin/products/components/create/admin-product-size-create-form.vue
- frontend/src/modules/admin/products/components/details/admin-product-size-details-form.vue
- frontend/src/modules/kiosk/products/models/product.model.ts
- frontend/src/modules/kiosk/products/services/products.service.ts
> feat: copy technical map

- frontend/src/modules/admin/additives/components/create/admin-additive-create-form.vue
- frontend/src/modules/admin/additives/components/list/admin-additives-list.vue
- frontend/src/modules/admin/additives/pages/admin-additive-create-page.vue
- frontend/src/modules/admin/products/components/create/admin-product-size-create-form.vue
- frontend/src/modules/admin/products/components/details/admin-product-sizes.vue
- frontend/src/modules/admin/products/pages/admin-product-size-create-page.vue
- frontend/src/modules/kiosk/products/models/product.model.ts
> feat: duplicate additives & productSizes

- frontend/src/modules/admin/provisions/components/create/admin-provision-create-form.vue
> fix: unit state not set

- backend/internal/modules/orders/orders.repository.go
- frontend/src/core/hooks/use-copy-technical-map.hooks.ts
- frontend/src/modules/admin/additives/components/list/admin-additives-list.vue
- frontend/src/modules/admin/products/components/details/admin-product-sizes.vue
- frontend/src/modules/admin/provisions/components/list/admin-provisions-list.vue
- frontend/src/modules/admin/store-orders/barista/components/admin-barista-orders-list.vue
- frontend/src/modules/admin/store-orders/barista/components/admin-barista-sub-order-details.vue
- frontend/src/modules/admin/store-orders/barista/components/admin-barista-suborders-list.vue
- frontend/src/modules/admin/store-orders/components/admin-orders-export.vue
- frontend/src/modules/admin/store-orders/components/list/admin-store-orders-list.vue
- frontend/src/modules/admin/store-orders/models/orders.models.ts
- frontend/src/modules/admin/store-orders/services/orders.service.ts
- frontend/src/modules/admin/store-products/services/store-products.service.ts
- frontend/src/modules/admin/stores/components/list/admin-stores-list.vue
- frontend/src/modules/admin/suppliers/components/details/admin-supplier-materials-form.vue
- frontend/src/modules/admin/warehouse-deliveries/components/create/admin-warehouse-deliveries-create-form.vue
- frontend/src/modules/admin/warehouse-deliveries/components/details/admin-warehouse-deliveries-details-form.vue
- frontend/src/modules/kiosk/cart/components/kiosk-cart-update-item.vue
- frontend/src/modules/kiosk/products/components/home/list/kiosk-home-products-loading.vue
> feat: added proper shift check for the reset display number in order

- frontend/src/core/hooks/use-copy-technical-map.hooks.ts
- frontend/src/modules/admin/provisions/components/create/admin-provision-create-form.vue
- frontend/src/modules/admin/provisions/components/details/admin-provision-update-form.vue
- frontend/src/modules/admin/provisions/models/provision.models.ts
- frontend/src/modules/admin/provisions/services/provisions.service.ts
- frontend/src/modules/admin/store-orders/display/components/admin-orders-display-list.vue
- frontend/src/modules/admin/store-orders/display/pages/admin-orders-display-page.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-details-additives-card.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-details-additives-section.vue
- frontend/src/modules/kiosk/products/pages/kiosk-product-page.vue
> feat: added tech map copy for provision and kiosk additives selection

- frontend/src/modules/admin/provisions/models/provision.models.ts
- frontend/src/modules/kiosk/cart/components/kiosk-cart-update-item.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-details-additives-card.vue
- frontend/src/modules/kiosk/products/components/details/kiosk-details-additives-section.vue
- frontend/src/modules/kiosk/products/pages/kiosk-product-page.vue
> feat: fixed issue when default additives added own price

- backend/internal/modules/orders/orders.repository.go
> fix: snap dates to day beginning/end

- frontend/src/core/hooks/use-print.hook.ts
- frontend/src/modules/admin/employees/pages/admin-employee-reassign-type-page.vue
- frontend/src/modules/admin/store-orders/barista/components/admin-barista-sub-order-details.vue
- frontend/src/modules/admin/store-orders/hooks/use-order-qr-print.hook.ts
- frontend/src/modules/admin/store-products/pages/admin-store-product-details-page.vue
> feat: added adjustments in Font naems, file names and layouting

- frontend/src/core/validators/password.validator.ts
- frontend/src/modules/admin/store-orders/hooks/use-order-qr-print.hook.ts
> feat: made ZPL output print smaller elements
